parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/34.h>
    #define CONFIG_WIRELESS

  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&studio_unlock": Studio
    "&caps_word": Caps Word

    "&kp LC(INS)": $$mdi:content-copy$$
    "&kp LC(X)": $$mdi:content-cut$$
    "&kp LS(INS)": $$mdi:content-paste$$
    "&kp LC(S)": $$mdi:content-save-outline$$

    "&kp LA(LS(N4))": $$mdi:cellphone-screenshot$$
    "&kp LA(LS(T))": $$mdi:console-line$$
    "&kp LC(SPACE)": $$mdi:rocket-launch$$
    "&kp LC(FSLH)": //
    "&kp LC(HOME)": Doc S
    "&kp LC(END)": Doc E
    "&kp LC(LA(LS(M)))": HDMI
    "&kp LC(LA(M))": DP

    "&swapper": AltTb
    "LS(LCTRL) LS(TAB)": { "t": $$mdi:keyboard-tab-reverse$$, "h": "" }
    "&kp LS(TAB)": { "t": $$mdi:keyboard-tab-reverse$$, "h": "" }
    "&dot_spc": Sntnce
    "&num_dance": { "t": "Smart"}
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&key_repeat": Rpt

    "&dbl_arrow": =>
    "&sgl_arrow": ->
    "&const_fn": JS ()

    "&hml LS(LALT)TAB": { "t": $$mdi:keyboard-tab$$, "h": "" }
    "&hml LS(LCTRL) LS(TAB)": { "t": $$mdi:keyboard-tab-reverse$$, "h": "" }
    "&hm_combo_lpar": { "t": "< (" }
    "&hm_combo_rpar": { "t": "> )"}
    "&kp LBKT": { "t": "{ ["}
    "&kp RBKT": { "t": "} ]"}

    "WORD_KEB": "wd-md"
    "WORD_PAS": "WdMd"
    "WORD_PTH": "wd/md"
    "WORD_UND": "wd_md"
    "CAPS_UND": "WD_MD"

    "NAV_BSPC": { t: $$mdi:backspace-outline$$, h: "word" }
    "&mt LC(DEL) DEL": { t: $$mdi:backspace-reverse-outline$$, h: "word" }

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_ldrsh: { align: top, o: 1.35 }

    combo_lt: { hidden: true }
    combo_gt: { hidden: true }
    combo_lbrc: { hidden: true }
    combo_rbrc: { hidden: true }
    combo_cancel: { align: top, o: 0.5 }
    combo_save: { align: bottom, o: 0.2 }
    combo_bootloader: { align: top, o: 0.35 }

  zmk_keycode_map:
    # custom mappings
    LALT: $$mdi:apple-keyboard-option$$
    LCTRL: $$mdi:apple-keyboard-control$$
    LGUI: $$mdi:apple-keyboard-command$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$

    BSPC: $$mdi:backspace-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    ESC: $$mdi:keyboard-esc$$
    RET: $$mdi:keyboard-return$$
    SPACE: $$mdi:keyboard-space$$
    LS(TAB): { "t": $$mdi:keyboard-tab-reverse$$, "h": "" }
    PAUSE_BREAK: Break

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    K_CANCEL: $$mdi:close-thick$$

    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_BRI_INC: $$mdi:brightness-4$$
    C_BRI_DEC: $$mdi:brightness-5$$

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _

    F1: $$mdi:keyboard-f1$$
    F2: $$mdi:keyboard-f2$$
    F3: $$mdi:keyboard-f3$$
    F4: $$mdi:keyboard-f4$$
    F5: $$mdi:keyboard-f5$$
    F6: $$mdi:keyboard-f6$$
    F7: $$mdi:keyboard-f7$$
    F8: $$mdi:keyboard-f8$$
    F9: $$mdi:keyboard-f9$$
    F10: $$mdi:keyboard-f10$$
    F11: $$mdi:keyboard-f11$$
    F12: $$mdi:keyboard-f12$$

draw_config:
  append_colon_to_layer_header: false
  dark_mode: false
  footer_text: "illusaen/zmk-config"
  glyph_tap_size: 16
  glyph_hold_size: 12
  glyph_shifted_size: 12
  legend_rel_y: 1
  outer_pad_w: 10
  outer_pad_h: 10
  small_pad: 4
  shrink_wide_legends: 4

  svg_style: |
    svg path { fill: inherit; }

    svg.keymap {
        --color-bg:      #7c6f64;
        --color-key:     #fbf1c7;
        --color-text:    #3c3836;
        --color-ghost:   #928374;
        --color-dendron: #d5c4a1;
        --color-held:    #bdae93;

        --color-nav:     #F0BD6A;
        --color-num:     #DA6C7B;
        --color-sys:     #D6FFB7;

        fill: var(--color-text);
        background-color: var(--color-bg);
        font-family: Inter, system-ui, sans-serif;
        font-size: 14px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        letter-spacing: 0.02em;
    }

    text.tap     { font-weight: 500; }
    text.hold    { font-weight: 400; font-size: 11px; color: var(--color-sys) }
    text.shifted { font-weight: 400; font-size: 11px; }
    text.combo, text.left, text.right, text.tl, text.tr, text.bl, text.br { font-size: 10px; }

    text.hold, text.bl, text.br    { text-anchor: middle; dominant-baseline: auto; }
    text.shifted, text.tl, text.tr { text-anchor: middle; dominant-baseline: hanging; }
    text.left, text.tl, text.bl    { text-anchor: start; }
    text.right, text.tr, text.br   { text-anchor: end; }

    text.layer-activator { text-decoration: underline; }
    text.combo.hold, text.combo.shifted, text.combo.left, text.combo.right { font-size: 8px; }

    text.label, text.footer {
        fill: var(--color-key);
        stroke: var(--color-bg);
        stroke-width: 4;
        paint-order: stroke;
    }
    text.label  { font-weight: bold; text-anchor: start; dominant-baseline: hanging; }
    text.footer { text-anchor: end; dominant-baseline: auto; }

    rect.key, rect.combo, rect.combo-separate { fill: var(--color-key); stroke-width: 0; }
    rect.held, rect.combo.held                { fill: var(--color-held); }
    .layer-Combos rect.key                    { fill: var(--color-ghost); font-size: 14px; }

    path.combo { stroke: var(--color-dendron); stroke-width: 2; stroke-dasharray: 2, 3; opacity: 0.45; fill: none; }

    text.tl, use.tl { fill: var(--color-fn); }
    text.tr, use.tr { fill: var(--color-nav); }
    text.bl, use.bl { fill: var(--color-num); }
    text.br, use.br { fill: var(--color-sys); }

    .keypos-31 text.hold { fill: var(--color-nav); }
    .keypos-32 text.hold { fill: var(--color-num); }
    # .keypos-32 text.tap  { fill: var(--color-num); }
    .keypos-33 text.hold { font-size: 15px; }

    .icon-tabler > path                             { fill: inherit; stroke: inherit; stroke-width: 2; }
    .icon-tabler > path[stroke="none"][fill="none"] { visibility: hidden; }

    @media (prefers-color-scheme: dark) {
        svg.keymap {
            --color-bg:      #a89984;
            --color-key:     #282828;
            --color-text:    #ebdbb2;
            --color-ghost:   #928374;
            --color-dendron: #504945;
            --color-held:    #665c54;

            --color-nav:     #F0BD6A;
            --color-num:     #DA6C7B;
            --color-sys:     #D6FFB7;
        }
    }
