parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"
    - "zmk-helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/totem.h>
    #include <zmk-helpers/key-labels/36.h>
    #define CONFIG_WIRELESS

  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word
    "&studio_unlock": Studio

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4

    "&kp LG(LC(LEFT))": Prev Desk
    "&kp LG(LC(RIGHT))": Next Desk
    "&kp LG(LC(LS(A)))": Pin App
    "&kp LG(LC(LS(Q)))": Pin Win

    "&js_fn": = () =>
    "&js_interp": "`${}`"
    "&dbl_a": =>
    "&sgl_a": ->

    "&kp LS(TAB)": Tab L
    "&kp LC(X)": Cut
    "&kp LG(X)": Cut
    "&kp LC(C)": Copy
    "&kp LG(C)": Copy
    "&kp LC(V)": Paste
    "&kp LG(V)": Paste
    "&kp LC(Z)": Undo
    "&kp LG(Z)": Undo
    "&kp LS(LC(Z))": Redo
    "&kp LG(LS(Z))": Redo
    "&kp LC(S)": Save
    "&kp LG(S)": Save
    "&kp LC(SPACE)": $$tabler:zoom$$
    "&kp LG(LS(S))": $$tabler:camera$$
    "&kp LG(LC(N4))": $$tabler:camera$$
    "&kp LC(SLASH)": //
    "&kp LG(SLASH)": //
    "&kp LC(LS(T))": $$tabler:terminal-2$$

    "&kp LA(LEFT)": $$material:text_select_move_back_character$$
    "&kp LA(RIGHT)": $$material:text_select_move_forward_character$$

    "&kp LC(DEL)": Del word
    "&kp LC(BSPC)": Back word

    "&kp LC(HOME)": Doc home
    "&kp LC(END)": Doc end

    "&num_word NUM": Num word
    "CASE_CAPS": Caps _
    "CASE_PATH": Caps /
    "SWAP": Swap
    "CANCEL": Cancel
    "WORD_PATH": Word /
    "WORD_UNDER": Word _
    "WORD_DASH": Word -
    "UNDER_C": { "t": "_", "h": "Cancel" }
    "SLASH_C": { "t": "/", "h": "Cancel" }
    "DASH_C": { "t": "-", "h": "Cancel" }

    "&copy_cut": { "t": "Copy", "h": "Cut" }
    "&comma_m": { "t": ",", "s": ";", "h": "<" }
    "&dot_m": { "t": ".", "s": ":", "h": ">" }
    "&brace": { "t": "{", "h": "}" }
    "&bracket": { "t": "[", "h": "]" }
    "&paren": { "t": "(", "h": ")" }
    "&swapper": Next Win
    "&dot_spc": Sentence
    "&num_dance": { "t": "Numword", "s": "Sticky Num" }
    "&magic_shift": { "t": Magic, "h": "Shift" }
    "&smart_mouse": Smart Mouse

    "&hml LS(LALT)TAB": Tab
    "&hm_combo_ldr": Lead
    "&hm_combo_ldrsh": Shift+Leader
    "&hm_combo_lpar": { "t": "(", "right": "<" }
    "&hm_combo_rpar": { "t": ")", "right": ">" }
    "&kp LBKT": { "t": "[", "right": "{" }
    "&kp RBKT": { "t": "]", "right": "}" }

    "&mmv MOVE_UP": Mouse ↑
    "&mmv MOVE_DOWN": Mouse ↓
    "&mmv MOVE_LEFT": Mouse ←
    "&mmv MOVE_RIGHT": Mouse →

    "&msc SCRL_UP": Scroll ↑
    "&msc SCRL_DOWN": Scroll ↓
    "&msc SCRL_LEFT": Scroll ←
    "&msc SCRL_RIGHT": Scroll →

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click
    "&mkp MB4": Back Click
    "&mkp MB5": Forward Click

  trans_legend: { "t": "", "type": "trans" }

  zmk_combos:
    combo_cut: { align: bottom, o: 0.15 }
    combo_cancel: { align: top, o: 1.35 }
    combo_numword: { align: top, o: 0.75 }
    combo_save: { align: bottom, o: 0.75 }

  zmk_keycode_map:
    # custom mappings
    LALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$

    BSPC: $$material:backspace$$
    DEL: $$tabler:http-delete$$
    ESC: $$mdi:keyboard-esc$$
    RET: $$material:keyboard_return$$
    SPACE: $$material:space_bar$$
    TAB: Tab

    PG_UP: $$phosphor:bold/file-arrow-up$$
    PG_DN: $$phosphor:bold/file-arrow-down$$
    HOME: $$material:keyboard_tab_rtl$$
    END: $$material:keyboard_tab$$

    UP: $$fa:solid/arrow-up$$
    DOWN: $$fa:solid/arrow-down$$
    LEFT: $$fa:solid/arrow-left$$
    RIGHT: $$fa:solid/arrow-right$$

    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: /
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: "-"
    NON_US_BACKSLASH: \
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PAUSE_BREAK: "Break"
    PERCENT: "%"
    PERIOD: .
    PIPE: "|"
    PIPE2: "|"
    PLUS: +
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: "'"
    SLASH: /
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: _
    UNDERSCORE: _

draw_config:
  append_colon_to_layer_header: false
  glyph_tap_size: 18
  glyph_hold_size: 15
  dark_mode: auto
  footer_text: "illusaen/zmk-config"
  svg_extra_style: |
    svg.keymap {
      font-family: Helvetica, Arial, sans-serif;
    }
    .trans {
      fill: #bbb !important;
    }

